In [ ]:
#Import scikit-learn dataset library
from sklearn import datasets

The dataset comprises 30 features (mean radius, mean texture, mean perimeter, mean area, mean smoothness, mean compactness, mean concavity, mean concave points, mean symmetry, mean fractal dimension, radius error, texture error, perimeter error, area error, smoothness error, compactness error, concavity error, concave points error, symmetry error, fractal dimension error, worst radius, worst texture, worst perimeter, worst area, worst smoothness, worst compactness, worst concavity, worst concave points, worst symmetry, and worst fractal dimension) and a target (type of cancer).

This data has two types of cancer classes: malignant (harmful) and benign (not harmful). Here, you can build a model to classify the type of cancer. The dataset is available in the scikit-learn library or you can also download it from the UCI Machine Learning Library.

In [ ]:
#Load dataset
cancer = datasets.load_breast_cancer()

In [ ]:
# print the names of the 13 features
print("Features: ", cancer.feature_names)

# print the label type of cancer('malignant' 'benign')
print("Labels: ", cancer.target_names)

Features:  ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
Labels:  ['malignant' 'benign']


In [ ]:
import numpy as np

In [ ]:
np.unique(cancer.target, return_counts=True)

(array([0, 1]), array([212, 357]))

In [ ]:
# Import train_test_split function
from sklearn.model_selection import train_test_split
import numpy as np

In [ ]:
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(cancer.data, cancer.target, test_size=0.3,random_state=109) # 70% training and 30% test

In [ ]:
np.unique(y_test,return_counts=True)

(array([0, 1]), array([ 63, 108]))

In [ ]:
#Import svm model
from sklearn.svm import SVC

In [ ]:
#Create a svm Classifier
clf = SVC(kernel='linear') # Linear Kernel

In [ ]:
#Train the model using the training sets
clf.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [ ]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.9649122807017544


In [ ]:
confusion_matrix(y_test,y_pred)

array([[ 61,   2],
       [  4, 104]])

# Apply SVC with Polynomial kernel

In [ ]:
# Create a SVC classifier using a polynomial kernel
svm_poly = SVC(kernel='poly')

In [ ]:
#Train the model using the training sets
svm_poly.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
#Predict the response for test dataset
y_pred_poly = svm_poly.predict(X_test)

In [ ]:
# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred_poly))

Accuracy: 0.9181286549707602


In [ ]:
confusion_matrix(y_test,y_pred_poly)

array([[ 49,  14],
       [  0, 108]])

In [ ]:
#Hyperparameter tuning for polynomial kernel 
parameters = {'C': [1,10,100],'degree': [2,4,5]}

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
svm_poly_tune = GridSearchCV(svm_poly, parameters,cv=5) 

In [ ]:
svm_poly_tune.fit(X_train,y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='poly', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [1, 10, 100], 'degree': [2, 4, 5]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
svm_poly_tune.best_params_

{'C': 100, 'degree': 4}

In [ ]:
svm_poly_tune.best_score_

0.9121202531645569

In [ ]:
pred_poly_tune=svm_poly_tune.predict(X_test)

In [ ]:
confusion_matrix(y_test,pred_poly_tune)

array([[ 57,   6],
       [  0, 108]])

In [ ]:
accuracy_score(y_test,pred_poly_tune)

0.9649122807017544

# Apply SVC with Radial kernel

In [ ]:
# Create a SVC classifier using a radial kernel
svm_rbf = SVC(kernel='rbf')

In [ ]:
svm_rbf.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
svm_rbf.score(X_train,y_train)

0.9045226130653267

In [ ]:
parameters = {'C': [1,10,100],'gamma': [0.0001,0.001,0.01,1,10,100]}

In [ ]:
svm_rbf_tune = GridSearchCV(svm_rbf, parameters,cv=5) 

In [ ]:
svm_rbf_tune.fit(X_train,y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [1, 10, 100],
                         'gamma': [0.0001, 0.001, 0.01, 1, 10, 100]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
svm_rbf_tune.best_params_

{'C': 1, 'gamma': 0.0001}

In [ ]:
svm_rbf_tune.best_score_

0.9271518987341771

In [ ]:
pred_rbf_tune=svm_rbf_tune.predict(X_test)

In [ ]:
confusion_matrix(y_test,pred_rbf_tune)

array([[ 59,   4],
       [  1, 107]])

In [ ]:
accuracy_score(y_test,pred_rbf_tune)

0.9707602339181286